identifier_name:
  excluded:
    - id
disabled_rules:
  - trailing_whitespace
  - comment_spacing
  - multiple_closures_with_trailing_closure
  - switch_case_alignment
cyclomatic_complexity:
  ignores_case_statements: true
function_body_length:
  warning: 60

